server:
  port: 7903
spring:
  application:
    name: bootdemo
  mvc:
    view:
      prefix: /
      suffix: .html
logging:
  config: classpath:log4j2.xml
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true